name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - main
trigger:
  branches:
    include:
      - main
stages:
  - stage: Build
    jobs:
      - job: Build
        displayName: Build app
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
            displayName: 'Install Node.js'

          - task: Cache@2
            displayName: Cache node_modules
            inputs:
              key: 'node_modules | "$(Agent.OS)" | $(Build.SourcesDirectory)/package.json'
              path: '$(Build.SourcesDirectory)/node_modules'
              cacheHitVar: MODULES_CACHE_RESTORED

          - script: |
              npm install
            displayName: 'Install node_modules'
            condition: ne(variables.MODULES_CACHE_RESTORED, 'true')

          - script: |
              npm run test
            displayName: 'Run tests'

          - script: |
              npm run audit-dependencies
            displayName: 'Audit dependencies'

          - script: |
              npm run build
            displayName: 'Build app'

          - script: |
              CI=true npm run test:ci
            displayName: 'Run unit tests'

          - task: PublishTestResults@2
            displayName: 'Publish test report'
            condition: succeededOrFailed()
            inputs:
              testRunner: JUnit
              testResultsFiles: '**/junit.xml'

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: 'build'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true
            displayName: 'Archive build'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
            displayName: 'Publish build'

  - stage: Deploy
    jobs:
      - job: deploy
        displayName: Build and Deploy Job
        condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
        pool:
          vmImage: ubuntu-latest
        variables:
          - group: ui-variables
        steps:
          - checkout: self
            submodules: true
          - task: AzureStaticWebApp@0
            inputs:
              azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
              # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
              app_location: '/' # App source code path
              api_location: '' # Api source code path - optional
              output_location: '' # Built app content directory - optional

